# Generated by Django 5.2.8 on 2025-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tenant_status_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
