# Generated by Django 5.2.8 on 2026-04-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciepient',
            new_name='recipient',
        ),
    ]
