# Generated by Django 5.2.8 on 2026-01-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='exipiry_date',
            new_name='expiry_date',
        ),
    ]
