# Generated by Django 5.2.8 on 2026-01-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_exipiry_date_announcement_expiry_date'),
        ('accounts', '0006_alter_user_profile_image'),
        ('classroom', '0005_timeslot_is_break_alter_timetableentry_subject_and_more'),
        ('users', '0004_remove_student_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='classroom.schoolclass')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('school_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='users.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentDailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academics.classdailyattendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='users.student')),
            ],
            options={
                'unique_together': {('class_attendance', 'student')},
            },
        ),
    ]
