# Generated by Django 5.2.8 on 2026-01-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassStudent',
        ),
    ]
