# Generated by Django 5.2.8 on 2026-01-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_timetable_timetableentry'),
        ('users', '0004_remove_student_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='classroom.subject'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='users.teacher'),
        ),
    ]
