# Generated by Django 5.2.8 on 2026-03-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatvideo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aichatmessage',
            old_name='contend',
            new_name='content',
        ),
    ]
