# Generated by Django 5.2.8 on 2026-01-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
    ]
